### ISSUE TITLE
Romanian Towns Tweaking

### ISSUE THREAD

**Issue by CowSi** [3meraldK/earthmc-dynmapcolor#5]
Towns in Romania do not have borders
![Screenshot (273)](https://github.com/3meraldK/earthmc-dynmap/assets/174946237/595ed298-0a38-4cf8-a988-5fcbe2fbc341)

**Comment by 3meraldK** [comment]
Per the latest changelog which can be [read here](https://github.com/3meraldK/earthmc-dynmap/releases/latest), "condominiums have no outline/border". This applies to Romania and other nations which are a part of more than one alliance. This is intended, but I will consider changing the design.
